#### Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#### Load Data

In [2]:
df = pd.read_csv("zomato_messy_data.csv")

In [3]:
df.head()

,Restaurant Name,Rating,Cuisine,Average Price,Average Delivery Time,Safety Measure,Location
0,Campus Bakers,4.3,"Bakery, Fast Food, Pizza, Sandwich, Burger",₹50 for one,36 min,Restaurant partner follows WHO protocol,Agra
1,Mama Chicken Mama Franky House,4,"North Indian, Mughlai, Rolls, Burger, Momos",₹50 for one,22 min,Follows all Max Safety measures to ensure your...,Agra
2,GMB - Gopika Sweets & Restaurant,4.2,"North Indian, South Indian, Chinese, Fast Food...",₹50 for one,27 min,Follows all Max Safety measures to ensure your...,Agra
3,Shree Bankey Bihari Misthan Bhandar,4.2,"Mithai, Street Food, South Indian, Chinese, Ic...",₹50 for one,28 min,Restaurant partner follows WHO protocol,Agra
4,Burger King,4.2,"Burger, Fast Food, Beverages",₹50 for one,26 min,Follows all Max Safety measures to ensure your...,Agra

In [4]:
df.tail()

,Restaurant Name,Rating,Cuisine,Average Price,Average Delivery Time,Safety Measure,Location
44886,Bowl 99,-,North Indian,₹350 for one,Opens tomorrow at 11am,Follows all Max Safety measures to ensure your...,Warangal
44887,Vegan Mart,-,"Juices, Beverages",₹350 for one,Opens tomorrow at 11am,Follows all Max Safety measures to ensure your...,Warangal
44888,Biryani Plaza,-,Biryani,₹350 for one,Opens tomorrow at 11am,Follows all Max Safety measures to ensure your...,Warangal
44889,Biryani Plaza,-,Biryani,₹350 for one,Opens tomorrow at 11am,Follows all Max Safety measures to ensure your...,Warangal
44890,Biryani Plaza,-,Biryani,₹350 for one,Opens tomorrow at 11am,Follows all Max Safety measures to ensure your...,Warangal

In [5]:
df.shape

(44891, 7)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44891 entries, 0 to 44890
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Restaurant Name        44891 non-null  object
 1   Rating                 44891 non-null  object
 2   Cuisine                44872 non-null  object
 3   Average Price          44891 non-null  object
 4   Average Delivery Time  44891 non-null  object
 5   Safety Measure         44891 non-null  object
 6   Location               44891 non-null  object
dtypes: object(7)
memory usage: 2.4+ MB

In [7]:
df.describe()

,Restaurant Name,Rating,Cuisine,Average Price,Average Delivery Time,Safety Measure,Location
count,44891,44891,44872,44891,44891,44891,44891
unique,35688,28,17580,28,398,2,98
top,Baskin Robbins - Ice Cream Desserts,4,North Indian,₹100 for one,30 min,Follows all Max Safety measures to ensure your...,Kolkata
freq,70,5733,2403,13019,1715,25726,1296

In [8]:
df.columns.tolist()

['Restaurant Name',
 'Rating',
 'Cuisine',
 'Average Price',
 'Average Delivery Time',
 'Safety Measure',
 'Location']

#### Cleaning Data

In [9]:
df.isnull().sum()

Restaurant Name           0
Rating                    0
Cuisine                  19
Average Price             0
Average Delivery Time     0
Safety Measure            0
Location                  0
dtype: int64

In [10]:
df = df.dropna(subset=['Cuisine'])

In [11]:
df.duplicated().sum()

140

In [12]:
df = df.drop_duplicates()

In [13]:
df['Rating'] = df['Rating'].astype(str).str.extract('(\d+\.\d+)')
df['Rating'] = df['Rating'].astype(float)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\admin\AppData\Local\Temp\ipykernel_4728\2883885787.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['Rating'] = df['Rating'].astype(str).str.extract('(\d+\.\d+)')

In [14]:
df

,Restaurant Name,Rating,Cuisine,Average Price,Average Delivery Time,Safety Measure,Location
0,Campus Bakers,4.3,"Bakery, Fast Food, Pizza, Sandwich, Burger",₹50 for one,36 min,Restaurant partner follows WHO protocol,Agra
1,Mama Chicken Mama Franky House,NaN,"North Indian, Mughlai, Rolls, Burger, Momos",₹50 for one,22 min,Follows all Max Safety measures to ensure your...,Agra
2,GMB - Gopika Sweets & Restaurant,4.2,"North Indian, South Indian, Chinese, Fast Food...",₹50 for one,27 min,Follows all Max Safety measures to ensure your...,Agra
3,Shree Bankey Bihari Misthan Bhandar,4.2,"Mithai, Street Food, South Indian, Chinese, Ic...",₹50 for one,28 min,Restaurant partner follows WHO protocol,Agra
4,Burger King,4.2,"Burger, Fast Food, Beverages",₹50 for one,26 min,Follows all Max Safety measures to ensure your...,Agra
...,...,...,...,...,...,...,...
44884,RV Tiffins And Fast Food,NaN,"South Indian, Street Food",₹350 for one,Opens tomorrow at 11am,Follows all Max Safety measures to ensure your...,Warangal
44885,Mom's Kitchen,NaN,North Indian,₹350 for one,Opens tomorrow at 11am,Follows all Max Safety measures to ensure your...,Warangal
44886,Bowl 99,NaN,North Indian,₹350 for one,Opens tomorrow at 11am,Follows all Max Safety measures to ensure your...,Warangal
44887,Vegan Mart,NaN,"Juices, Beverages",₹350 for one,Opens tomorrow at 11am,Follows all Max Safety measures to ensure your...,Warangal
44888,Biryani Plaza,NaN,Biryani,₹350 for one,Opens tomorrow at 11am,Follows all Max Safety measures to ensure your...,Warangal

In [20]:
df['Rating'] = df['Rating'].fillna(df['Rating'].mean()).round(1)

In [35]:
df['Average Price'] = df['Average Price'].astype(str).str.extract('(\d+)')
df['Average Price'] = df['Average Price'].astype(float)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\admin\AppData\Local\Temp\ipykernel_4728\2912681565.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['Average Price'] = df['Average Price'].astype(str).str.extract('(\d+)')

In [37]:
df['Average Delivery Time'] = df['Average Delivery Time'].astype(str).str.extract('(\d+)')
df['Average Delivery Time'] = df['Average Delivery Time'].astype(float)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\admin\AppData\Local\Temp\ipykernel_4728\4147320632.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['Average Delivery Time'] = df['Average Delivery Time'].astype(str).str.extract('(\d+)')

In [39]:
print(df[['Average Price', 'Average Delivery Time']].isnull().sum())

Average Price              19
Average Delivery Time    1531
dtype: int64

In [40]:
cols = ['Average Price', 'Average Delivery Time']
df[cols] = df[cols].fillna(0).astype(int)

In [44]:
df = df[(df['Average Price'] != 0) & (df['Average Delivery Time'] != 0)]

,Restaurant Name,Rating,Cuisine,Average Price,Average Delivery Time,Safety Measure,Location
0,Campus Bakers,4.3,"Bakery, Fast Food, Pizza, Sandwich, Burger",50,36,Restaurant partner follows WHO protocol,Agra
1,Mama Chicken Mama Franky House,3.9,"North Indian, Mughlai, Rolls, Burger, Momos",50,22,Follows all Max Safety measures to ensure your...,Agra
2,GMB - Gopika Sweets & Restaurant,4.2,"North Indian, South Indian, Chinese, Fast Food...",50,27,Follows all Max Safety measures to ensure your...,Agra
3,Shree Bankey Bihari Misthan Bhandar,4.2,"Mithai, Street Food, South Indian, Chinese, Ic...",50,28,Restaurant partner follows WHO protocol,Agra
4,Burger King,4.2,"Burger, Fast Food, Beverages",50,26,Follows all Max Safety measures to ensure your...,Agra
...,...,...,...,...,...,...,...
44884,RV Tiffins And Fast Food,3.9,"South Indian, Street Food",350,11,Follows all Max Safety measures to ensure your...,Warangal
44885,Mom's Kitchen,3.9,North Indian,350,11,Follows all Max Safety measures to ensure your...,Warangal
44886,Bowl 99,3.9,North Indian,350,11,Follows all Max Safety measures to ensure your...,Warangal
44887,Vegan Mart,3.9,"Juices, Beverages",350,11,Follows all Max Safety measures to ensure your...,Warangal
44888,Biryani Plaza,3.9,Biryani,350,11,Follows all Max Safety measures to ensure your...,Warangal

In [46]:
df.describe()

             Rating  Average Price  Average Delivery Time
count  43152.000000   43152.000000           43152.000000
mean       3.911633     173.327076              31.057865
std        0.310813      88.284754              11.968707
min        2.400000      10.000000               1.000000
25%        3.800000     100.000000              24.000000
50%        3.900000     150.000000              31.000000
75%        4.100000     200.000000              38.000000
max        4.900000     900.000000             190.000000

In [47]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [49]:
df.to_csv("clean_zomato.csv", index=False)

#### EDA

In [50]:
df.sort_values("rating", ascending=False).head(10)

,restaurant_name,rating,cuisine,average_price,average_delivery_time,safety_measure,location
11965,Rambhai Special Butter Patties,4.9,"Street Food, Beverages",100,29,Restaurant partner follows WHO protocol,Firozabad
32964,Rasoi Ghar Se,4.9,"North Indian, Mithai, Chinese, Street Food",100,32,Restaurant partner follows WHO protocol,Palakkad
27235,Hangyo Ice Cream,4.9,"Ice Cream, Desserts",100,8,Follows all Max Safety measures to ensure your...,Manipal
40328,Cake Waves,4.9,"Bakery, Fast Food, Desserts",150,24,Follows all Max Safety measures to ensure your...,Trichy
5046,Ibaco,4.8,Ice Cream,200,21,Restaurant partner follows WHO protocol,Belgaum
39466,Kudrati Kahumbo,4.8,"Shake, Beverages",400,34,Follows all Max Safety measures to ensure your...,Surat
27196,Natural Ice Cream,4.8,"Ice Cream, Desserts",200,11,Restaurant partner follows WHO protocol,Manipal
1863,Herbi Vore,4.8,"Fast Food, North Indian",200,36,Restaurant partner follows WHO protocol,Aligarh
12154,Sree Ramtilkut Bhandar (Since 1911),4.8,Desserts,200,24,Follows all Max Safety measures to ensure your...,Gaya
42667,Oasis Vegan Treats,4.8,"Healthy Food, Salad",250,43,Follows all Max Safety measures to ensure your...,Vadodara

In [51]:
df.sort_values("average_price", ascending=False).head(10)

,restaurant_name,rating,cuisine,average_price,average_delivery_time,safety_measure,location
41696,Palki Khana - By Shiv Niwas Palace,3.9,"North Indian, European, Italian, Mediterranean...",900,6,Follows all Max Safety measures to ensure your...,Udaipur
12580,Feliz - Double Tree By Hilton,3.9,"Goan, Seafood, Mangalorean",900,61,Restaurant partner follows WHO protocol,Goa
41711,Arjuna,3.9,"Modern Indian, North Indian, Desserts",850,6,Follows all Max Safety measures to ensure your...,Udaipur
34442,Heist Night Life,3.9,"Continental, Chinese, North Indian, Pizza, Sea...",850,37,Restaurant partner follows WHO protocol,Puducherry
41412,Nova,3.9,"North Indian, Fast Food, Desserts, Beverages",800,40,Follows all Max Safety measures to ensure your...,Udaipur
26486,Mamagoto,3.7,"Chinese, Sushi, Asian, Japanese, Thai, Salad, ...",800,37,Restaurant partner follows WHO protocol,Ludhiana
18319,A Sheridan Inn,3.9,"North Indian, Biryani, Chinese, Pizza, Burger,...",800,21,Follows all Max Safety measures to ensure your...,Jalandhar
41702,Firki,3.9,"North Indian, Modern Indian, Asian, Bar Food, ...",800,6,Follows all Max Safety measures to ensure your...,Udaipur
34151,Magadhi,3.9,"Chinese, North Indian, Sichuan",800,52,Follows all Max Safety measures to ensure your...,Patna
32501,Qbic Cafe & Bar,3.9,"Chinese, North Indian, Continental, Italian, M...",800,39,Follows all Max Safety measures to ensure your...,NCR

In [52]:
df.groupby("location").size()

location
Agra             600
Ahmedabad        600
Ajmer            401
Alappuzha         45
Aligarh          282
                ...
Varanasi         719
Vellore          184
Vijayawada       707
Visakhapatnam    169
Warangal         276
Length: 98, dtype: int64

In [53]:
df['cuisine'].value_counts().head(10)

cuisine
North Indian             2262
Bakery                   1107
South Indian              738
Bakery, Desserts          700
Street Food               624
North Indian, Chinese     617
Biryani                   463
Ice Cream, Desserts       434
Fast Food                 412
Pizza, Fast Food          412
Name: count, dtype: int64